export const ADD_BORROW = 'ADD_BORROW'

export const DELETE_BORROW = 'DELETE_BORROW'

export const ADD_SHOPLIST = 'ADD_SHOPLIST'

export const DELETE_SHOPLIST = 'DELETE_SHOPLIST'

export const UPDATE_DISTANCE = 'UPDATE_DISTANCE'
